services:
  - type: web
    name: guardian-bot
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 3000 